#docker-compose.ymlversion: '3.8'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    scheduler:
        image: apache/airflow:2.5.0
        # entrypoint: "airflow scheduler"
        command: scheduler
        # restart_policy:
        #     condition: on-failure
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./src/dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - /Users/Licious/project/ulb/dw/di/data_3:/staging
    webserver:
        image: pacific31/airflow:2.5
        entrypoint: /opt/airflow/scripts/entrypoint.sh
        # restart_policy:
        #     condition: on-failure
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./src/dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8081:8080"