#docker-compose.ymlversion: '3.8'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    scheduler:
        image: pacific31/airflow:2.6
        container_name: scheduler
        restart: always
        # entrypoint: "airflow scheduler"
        entrypoint: bash -c 'airflow db init; airflow scheduler'
        # entrypoint: /opt/airflow/scripts/entrypoint_scheduler.sh
        depends_on:
            - postgres
            # - initdb
        env_file:
            - .env
        environment:
            - AIRFLOW_CONN_MYSQL_DEFAULT=mysql://tpcds:tpcds@host.docker.internal:3306/master?%7B%22allow_local_infile%22%3A%20true%7D
            - AIRFLOW_CONN_MYSQL_CLOUD=mysql://DB00008858:Pac@3101@tpc-di-v2-db00008858.mdb0002659.db.skysql.net:5001/staging?%7B%22charset%22%3A%20%22utf8%22%2C%20%22cursor%22%3A%20%22sscursor%22%2C%20%22local_infile%22%3A%20true%2C%20%22ssl%22%3A%20%7B%22ca%22%3A%20%22%2Fskysql_chain.pem%22%7D%7D
        volumes:
            - ./src/dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - /Users/Licious/project/ulb/dw/di/tpcdi-kit/Tools/data/7:/staging
        #     - ./scripts:/opt/airflow/scripts
    webserver:
        image: pacific31/airflow:2.6
        container_name: web
        restart: always
        entrypoint: /opt/airflow/scripts/entrypoint.sh
        depends_on:
            - postgres
            - scheduler
            # - initdb
        env_file:
            - .env
        environment:
            - AIRFLOW_CONN_MYSQL_DEFAULT=mysql://tpcds:tpcds@host.docker.internal:3306/master?%7B%22allow_local_infile%22%3A%20true%7D
            - AIRFLOW_CONN_MYSQL_CLOUD=mysql://DB00008858:Pac@3101@tpc-di-v2-db00008858.mdb0002659.db.skysql.net:5001/staging?%7B%22charset%22%3A%20%22utf8%22%2C%20%22cursor%22%3A%20%22sscursor%22%2C%20%22local_infile%22%3A%20true%2C%20%22ssl%22%3A%20%7B%22ca%22%3A%20%22%2Fskysql_chain.pem%22%7D%7D
        volumes:
            - ./src/dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
        #     - ./scripts:/opt/airflow/scripts
        ports:
            - "8081:8080"

    # initdb:
    #     image: pacific31/airflow:2.5
    #     user: root
    #     restart: "no"
    #     volumes:
    #         - ./src/dags:/opt/airflow/dags
    #         - ./logs:/opt/airflow/logs
    #         - ./scripts:/opt/airflow/scripts
    #     entrypoint: ["bash", "-c", "chmod -R 777 /opt/airflow/"]


# docker cp  /Users/Licious/project/ulb/dw/di/data_3 new-webserver-1:/staging
# docker cp {file} web:/staging
# docker cp {file} scheduler:/staging
